export const actionType = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    SUBMIT_CONTACT_INFO: 'SUBMIT_CONTACT_INFO',
    DELETE_CONTACT_INFO: 'DELETE_CONTACT_INFO',
    CHECKOUT: 'CHECKOUT'
}